apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - agentgateway-backend-anthropic.yaml
  - agentgateway-backend-openai.yaml

secretGenerator:
  - name: anthropic-secret
    namespace: agentgateway-system
    options:
      disableNameSuffixHash: true
    envs:
      - .anthropic.env

  - name: openai-secret
    namespace: agentgateway-system
    options:
      disableNameSuffixHash: true
    envs:
      - .openai.env