apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lab2-kagent
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ai-agents-training
  path: ./lab2/kagent
  prune: true
  targetNamespace: kagent
