apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kagent/
secretGenerator:
  - name: anthropic-api-key
    namespace: kagent
    options:
      disableNameSuffixHash: true
    envs:
      - .env
